# Generated by Django 5.0 on 2024-01-15 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mcq", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_eng", models.CharField(max_length=200)),
                ("question_urd", models.CharField(max_length=200)),
                (
                    "question_type",
                    models.CharField(
                        choices=[("short", "short"), ("long", "long")], max_length=20
                    ),
                ),
                ("subject", models.CharField(max_length=20)),
                ("grade", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="TotalPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="McqOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("op_a", models.CharField(max_length=100)),
                ("op_b", models.CharField(max_length=100)),
                ("op_c", models.CharField(max_length=100)),
                ("op_d", models.CharField(max_length=100)),
                (
                    "mcq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionpaper.multiplechoicequestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrueOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("true_option", models.CharField(max_length=100)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionpaper.mcqoption",
                    ),
                ),
            ],
        ),
    ]
