# Generated by Django 5.0 on 2024-01-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionpaper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
