# Generated by Django 5.0 on 2024-01-16 05:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questionpaper", "0002_questionbank_approved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mcqoption",
            old_name="mcq",
            new_name="options",
        ),
        migrations.RenameField(
            model_name="trueoption",
            old_name="option",
            new_name="trueoption",
        ),
    ]
