# Generated by Django 5.0 on 2024-01-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionpaper", "0003_rename_mcq_mcqoption_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcqoption",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="grade",
            field=models.CharField(
                choices=[
                    ("", "--select--"),
                    ("10", "10"),
                    ("9", "9"),
                    ("8", "8"),
                    ("7", "7"),
                    ("6", "6"),
                    ("5", "5"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="question_type",
            field=models.CharField(
                choices=[("", "--select--"), ("short", "short"), ("long", "long")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="subject",
            field=models.CharField(
                choices=[
                    ("", "--select--"),
                    ("islamiyat", "Islamiyat"),
                    ("urdu", "Urdu"),
                    ("physics", "Physics"),
                    ("chemistry", "Chemsitry"),
                    ("bioloby", "Biology"),
                    ("math", "Mathematics"),
                    ("english", "English"),
                    ("pakstudy", "Pakistan Study"),
                ],
                max_length=20,
            ),
        ),
    ]
