# Generated by Django 5.0 on 2024-01-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionpaper", "0004_mcqoption_approved_alter_questionbank_grade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mcqoption",
            name="approved",
        ),
        migrations.AddField(
            model_name="trueoption",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
