# Generated by Django 5.0 on 2024-01-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionpaper", "0007_alter_multiplechoicequestion_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionbank",
            name="question_eng",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
