# Generated by Django 5.0 on 2024-01-26 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "questionpaper",
            "0011_questiontype_question_multiplechoicequestions_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questiontype",
            name="question",
        ),
        migrations.RemoveField(
            model_name="shortanswerquestion",
            name="questiontype_ptr",
        ),
        migrations.RemoveField(
            model_name="truefalsequestion",
            name="questiontype_ptr",
        ),
        migrations.DeleteModel(
            name="MultipleChoiceQuestions",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="ShortAnswerQuestion",
        ),
        migrations.DeleteModel(
            name="QuestionType",
        ),
        migrations.DeleteModel(
            name="TrueFalseQuestion",
        ),
    ]
