# Generated by Django 5.0 on 2024-01-26 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionpaper", "0012_remove_questiontype_question_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="KuestionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_question", models.BooleanField(default=False)),
                ("long_question", models.BooleanField(default=False)),
                ("analytical_question", models.BooleanField(default=False)),
                (
                    "kuestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionpaper.kuestion",
                    ),
                ),
            ],
        ),
    ]
