# Generated by Django 5.0 on 2024-01-30 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questionpaper", "0013_kuestion_kuestiontype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kuestiontype",
            name="kuestion",
        ),
        migrations.DeleteModel(
            name="Kuestion",
        ),
        migrations.DeleteModel(
            name="KuestionType",
        ),
    ]
