# Generated by Django 5.0 on 2024-01-30 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionpaper", "0014_remove_kuestiontype_kuestion_delete_kuestion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short", models.BooleanField(default=False)),
                ("long", models.BooleanField(default=False)),
                ("analytical", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="questionbank",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("", "--select--"),
                    ("1", "Chapter-1"),
                    ("2", "Chapter-2"),
                    ("3", "Chapter-3"),
                    ("4", "Chapter-4"),
                    ("5", "Chapter-5"),
                    ("6", "Chapter-6"),
                    ("7", "Chapter-7"),
                    ("8", "Chapter-8"),
                    ("9", "Chapter-9"),
                    ("10", "Chapter-10"),
                ],
                default="1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="question_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="questionpaper.questionselection",
            ),
        ),
    ]
