# Generated by Django 5.0 on 2024-01-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionpaper", "0016_rename_question_type_questionbank_question_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="question_type",
            field=models.CharField(
                choices=[("", "--select--"), ("short", "Short")],
                default="short",
                max_length=20,
            ),
        ),
    ]
