# Generated by Django 5.0 on 2024-01-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionpaper", "0017_questionbank_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionselection",
            name="i2018",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questionselection",
            name="i2019",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questionselection",
            name="i2020",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questionselection",
            name="i2021",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questionselection",
            name="i2022",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questionselection",
            name="ii2018",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questionselection",
            name="ii2019",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questionselection",
            name="ii2020",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questionselection",
            name="ii2021",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questionselection",
            name="ii2022",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="question_type",
            field=models.CharField(
                choices=[("", "--select--"), ("short", "Short")], max_length=20
            ),
        ),
    ]
