# Generated by Django 5.0 on 2024-01-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "questionpaper",
            "0018_questionselection_i2018_questionselection_i2019_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="multiplechoicequestion",
            old_name="mcq",
            new_name="mcq_eng",
        ),
        migrations.RemoveField(
            model_name="questionbank",
            name="question_type",
        ),
        migrations.AddField(
            model_name="mcqoption",
            name="op_au",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mcqoption",
            name="op_bu",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mcqoption",
            name="op_cu",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mcqoption",
            name="op_du",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="multiplechoicequestion",
            name="mcq_urd",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("", "--select--"),
                    ("1", "Chapter-1"),
                    ("2", "Chapter-2"),
                    ("3", "Chapter-3"),
                    ("4", "Chapter-4"),
                    ("5", "Chapter-5"),
                    ("6", "Chapter-6"),
                    ("7", "Chapter-7"),
                    ("8", "Chapter-8"),
                    ("9", "Chapter-9"),
                    ("10", "Chapter-10"),
                ],
                max_length=20,
            ),
        ),
    ]
