# Generated by Django 5.0 on 2024-02-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionpaper", "0019_rename_mcq_multiplechoicequestion_mcq_eng_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiplechoicequestion",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("", "--select--"),
                    ("1", "Chapter-1"),
                    ("2", "Chapter-2"),
                    ("3", "Chapter-3"),
                    ("4", "Chapter-4"),
                    ("5", "Chapter-5"),
                    ("6", "Chapter-6"),
                    ("7", "Chapter-7"),
                    ("8", "Chapter-8"),
                    ("9", "Chapter-9"),
                    ("10", "Chapter-10"),
                ],
                default="1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mcqoption",
            name="op_au",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mcqoption",
            name="op_bu",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mcqoption",
            name="op_cu",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mcqoption",
            name="op_du",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
