# Generated by Django 5.0 on 2024-02-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "questionpaper",
            "0020_multiplechoicequestion_chapter_alter_mcqoption_op_au_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("", "--select--"),
                    ("1", "Chapter-1"),
                    ("2", "Chapter-2"),
                    ("3", "Chapter-3"),
                    ("4", "Chapter-4"),
                    ("5", "Chapter-5"),
                    ("6", "Chapter-6"),
                    ("7", "Chapter-7"),
                    ("8", "Chapter-8"),
                    ("9", "Chapter-9"),
                    ("10", "Chapter-10"),
                ],
                max_length=20,
            ),
        ),
    ]
