# Generated by Django 5.0 on 2024-02-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionpaper", "0021_alter_multiplechoicequestion_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="mcq_urd",
            field=models.CharField(max_length=200),
        ),
    ]
