# Generated by Django 5.0 on 2024-02-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionpaper", "0022_alter_multiplechoicequestion_mcq_urd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="mcq_eng",
            field=models.CharField(max_length=200),
        ),
    ]
