# Generated by Django 5.0 on 2024-02-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_userprofile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="img",
            field=models.ImageField(
                blank=True, default="default_pic.png", upload_to="images"
            ),
        ),
    ]
